version: '3'

volumes:
  produto-ms-data: { }

services:
  produto-ms-postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      POSTGRES_DB: erp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - produto-ms-data:/var/lib/postgresql

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24